# Generated by Django 5.0.3 on 2024-06-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='lname',
            new_name='username',
        ),
    ]
